name: server
version: '${project.version}'
main: org.server.untitled.Main
commands:
  jump:
    description: teleport
  scoreboard:
    description: create scoreboard
  emerald:
    description: eco emerald